package goserve

type Computer struct {
	Status                string `json:"__status,omitempty"`
	Asset                 string `json:"asset,omitempty"`
	AssetTag              string `json:"asset_tag,omitempty"`
	Assigned              string `json:"assigned,omitempty"`
	AssignmentTo          string `json:"assigned_to,omitempty"`
	AssignmentGroup       string `json:"assignment_group,omitempty"`
	Attributes            string `json:"attributes,omitempty"`
	BusinessCrit          string `json:"busines_criticality,omitempty"`
	CanPrint              string `json:"can_print,omitempty"`
	Category              string `json:"category,omitempty"`
	CDROM                 string `json:"cd_rom,omitempty"`
	CDSpeed               string `json:"cd_speed,omitempty"`
	ChangeControl         string `json:"change_control,omitempty"`
	ChasisType            string `json:"chassis_type,omitempty"`
	CheckedIn             string `json:"checked_in,omitempty"`
	CheckedOut            string `json:"checked_out,omitempty"`
	Comments              string `json:"comments,omitempty"`
	Company               string `json:"company,omitempty"`
	CorrelationID         string `json:"correlation_id,omitempty"`
	Cost                  string `json:"cost,omitempty"`
	CostCC                string `json:"cost_cc,omitempty"`
	CostCenter            string `json:"cost_center,omitempty"`
	CPUCoreCount          string `json:"cpu_core_count,omitempty"`
	CPUCoreThread         string `json:"cpu_core_thread,omitempty"`
	CPUCount              string `json:"cpu_count,omitempty"`
	CPUManufacturer       string `json:"cpu_manufacturer,omitempty"`
	CPUName               string `json:"cpu_name,omitempty"`
	COUSpeed              string `json:"cpu_speed,omitempty"`
	CPUType               string `json:"cpu_type,omitempty"`
	DefaultGateway        string `json:"default_gateway,omitempty"`
	DeliveryDate          string `json:"delivery_date,omitempty"`
	Department            string `json:"department,omitempty"`
	Depot                 string `json:"depot,omitempty"`
	DiscoverySource       string `json:"discovery_source,omitempty"`
	DiskSpace             string `json:"disk_space,omitempty"`
	DNSDomain             string `json:"dns_domain,omitempty"`
	Due                   string `json:"due,omitempty"`
	DueIn                 string `json:"due_in,omitempty"`
	FaultCount            string `json:"fault_count,omitempty"`
	FirstDiscovered       string `json:"first_discovered,omitempty"`
	Floppy                string `json:"floppy,omitempty"`
	FormFactor            string `json:"form_factor,omitempty"`
	FQDN                  string `json:"fqdn,omitempty"`
	GLAccount             string `json:"gl_account,omitempty"`
	HardwareStatus        string `json:"hardware_status,omitempty"`
	HardwareSubstatus     string `json:"hardware_substatus,omitempty"`
	InstallDate           string `json:"install_date,omitempty"`
	InstallStatus         string `json:"install_status,omitempty"`
	InvoiceNumber         string `json:"invoice_number,omitempty"`
	IPAddress             string `json:"ip_address,omitempty"`
	Justification         string `json:"justification,omitempty"`
	LastDiscovered        string `json:"last_discovered,omitempty"`
	LeaseID               string `json:"lease_id,omitempty"`
	Loaner                string `json:"loaner,omitempty"`
	Location              string `json:"location,omitempty"`
	MacAddress            string `json:"mac_address,omitempty"`
	MaintenanceSchedule   string `json:"maintenance_schedule,omitempty"`
	ManagedBy             string `json:"managed_by,omitempty"`
	MAnufacturer          string `json:"manufacturer,omitempty"`
	MetricType            string `json:"metric_type,omitempty"`
	ModelID               string `json:"model_id,omitempty"`
	ModelNumber           string `json:"model_number,omitempty"`
	Monitor               string `json:"monitor,omitempty"`
	Name                  string `json:"name,omitempty"`
	ObjectID              string `json:"object_id,omitempty"`
	OperationalStatus     string `json:"operational_status,omitempty"`
	OrderDate             string `json:"order_date,omitempty"`
	OS                    string `json:"os,omitempty"`
	OSAddress             string `json:"os_address_width,omitempty"`
	OSDomain              string `json:"os_domain,omitempty"`
	OSServicePack         string `json:"os_service_pack,omitempty"`
	OSVersion             string `json:"os_version,omitempty"`
	OwnedBy               string `json:"owned_by,omitempty"`
	PONum                 string `json:"po_number,omitempty"`
	Processor             string `json:"processor,omitempty"`
	PurchaseDate          string `json:"purchase_date,omitempty"`
	RAM                   string `json:"ram,omitempty"`
	Schedule              string `json:"schedule,omitempty"`
	SerialNumber          string `json:"serial_number,omitempty"`
	ShortDescription      string `json:"short_description,omitempty"`
	SkipSync              string `json:"skip_sync,omitempty"`
	StartDate             string `json:"start_date,omitempty"`
	Subcategory           string `json:"subcategory,omitempty"`
	SupportGroup          string `json:"support_group,omitempty"`
	SupportedBy           string `json:"supported_by,omitempty"`
	SysClassName          string `json:"sys_class_name,omitempty"`
	SysClassPath          string `json:"sys_class_path,omitempty"`
	SysCreatedBy          string `json:"sys_created_by,omitempty"`
	SysCreatedOn          string `json:"sys_created_on,omitempty"`
	SysDomain             string `json:"sys_domain,omitempty"`
	SysDomainPath         string `json:"sys_domain_path,omitempty"`
	SysID                 string `json:"sys_id,omitempty"`
	SysModCount           string `json:"sys_mod_count,omitempty"`
	SysTags               string `json:"sys_tags,omitempty"`
	SysUpdatedBy          string `json:"sys_updated_by,omitempty"`
	SysUpdatedOn          string `json:"sys_updated_on,omitempty"`
	UActive               string `json:"u_active,omitempty"`
	UAssignmentGroup      string `json:"u_assignment_group,omitempty"`
	UBIOSSerial           string `json:"u_bios_serial_number,omitempty"`
	UCalculatedUser       string `json:"u_calculated_user,omitempty"`
	UChasisSerial         string `json:"u_chasis_serial_number,omitempty"`
	UCM12Domain           string `json:"u_cm12_domain,omitempty"`
	UCM12InstallDate      string `json:"u_cm_12_installed_date,omitempty"`
	UCM12Username         string `json:"u_cm_12_user_name,omitempty"`
	UComments             string `json:"u_comments,omitempty"`
	UComputerName         string `json:" u_computer_name,omitempty"`
	UCurrentLoanerRequest string `json:"u_current_loaner_request,omitempty"`
	UID                   string `json:"u_id,omitempty"`
	ULastHWDate           string `json:"u_last_hw_inventory_date,omitempty"`
	ULastLoggedOn         string `json:"u_last_logged_on,omitempty"`
	ULastLoggedUser       string `json:"u_last_logged_on_user,omitempty"`
	UMacAddress           string `json:"u_mac_address,omitempty"`
	UNumOfProcessors      string `json:"u_number_of_processors,omitempty"`
	UTopConsoleUser       string `json:"u_top_console_user,omitempty"`
	UType                 string `json:"u_type,omitempty"`
	UUpgrade              string `json:"u_upgrade_eligibility,omitempty"`
	UWarrantyType         string `json:"u_warranty_type,omitempty"`
	Unverified            string `json:"unverified,omitempty"`
	UsedFor               string `json:"used_for,omitempty"`
	Variables             string `json:"variables":[],"vendor,omitempty"`
	Virtual               string `json:"virtual,omitempty"`
	WarrantyExpiration    string `json:"warranty_expiration,omitempty"`
}
