package goserve

type User struct {
	Status             string `json:"__status,omitempty"`
	AccRoles           string `json:"accumulated_roles,omitempty"`
	Active             string `json:"active,omitempty"`
	Auditor            string `json:"auditor,omitempty"`
	AvDailyFTE         string `json:"average_daily_fte,omitempty"`
	Building           string `json:"building,omitempty"`
	CalendarInt        string `json:"calendar_integration,omitempty"`
	City               string `json:"city,omitempty"`
	Company            string `json:"company,omitempty"`
	CostCenter         string `json:"cost_center,omitempty"`
	Country            string `json:"country,omitempty"`
	DateFormat         string `json:"date_format,omitempty"`
	DefaultPerspective string `json:"default_perspective,omitempty"`
	Department         string `json:"department,omitempty"`
	Email              string `json:"email,omitempty"`
	EmployeeNumber     string `json:"employee_number,omitempty"`
	FailedAttempts     string `json:"failed_attempts,omitempty"`
	FirstName          string `json:"first_name,omitempty"`
	Gender             string `json:"gender,omitempty"`
	HomePhone          string `json:"home_phone,omitempty"`
	InternalIntUser    string `json:"internal_integration_user,omitempty"`
	Intro              string `json:"introduction,omitempty"`
	LastLogin          string `json:"last_login,omitempty"`
	LastLoginTime      string `json:"last_login_time,omitempty"`
	LastName           string `json:"last_name,omitempty"`
	LDAPServer         string `json:"ldap_server,omitempty"`
	Location           string `json:"location,omitempty"`
	LockedOut          string `json:"locked_out,omitempty"`
	Manager            string `json:"manager,omitempty"`
	MiddleName         string `json:"middle_name,omitempty"`
	MobilePhone        string `json:"mobile_phone,omitempty"`
	Name               string `json:"name,omitempty"`
	Notification       string `json:"notification,omitempty"`
	PassNeedsReset     string `json:"password_needs_reset,omitempty"`
	Phone              string `json:"phone,omitempty"`
	Photo              string `json:"photo,omitempty"`
	PreferredLanguage  string `json:"preferred_language,omitempty"`
	Roles              string `json:"roles,omitempty"`
	Schedule           string `json:"schedule,omitempty"`
	Source             string `json:"source,omitempty"`
	SSOSource          string `json:"sso_source,omitempty"`
	State              string `json:"state,omitempty"`
	Street             string `json:"street,omitempty"`
	SysClassName       string `json:"sys_class_name,omitempty"`
	SysCreatedBy       string `json:"sys_created_by,omitempty"`
	SysCreatedOn       string `json:"sys_created_on,omitempty"`
	SysDomain          string `json:"sys_domain,omitempty"`
	SysID              string `json:"sys_id,omitempty"`
	SysModCount        string `json:"sys_mod_count,omitempty"`
	SysTags            string `json:"sys_tags,omitempty"`
	SysUpdatedBy       string `json:"sys_updated_by,omitempty"`
	SysUpdatedOn       string `json:"sys_updated_on,omitempty"`
	TimeFormat         string `json:"time_format,omitempty"`
	TimeSheetPol       string `json:"time_sheet_policy,omitempty"`
	TimeZone           string `json:"time_zone,omitempty"`
	Title              string `json:"title,omitempty"`
	UDefaultGroup      string `json:"u_default_group,omitempty"`
	UDepartment        string `json:"u_department,omitempty"`
	UDivision          string `json:"u_division,omitempty"`
	UOrginaization     string `json:"u_organization,omitempty"`
	UPosition          string `json:"u_position,omitempty"`
	UTeam              string `json:"u_team,omitempty"`
	Username           string `json:"user_name,omitempty"`
	UserPassword       string `json:"user_password,omitempty"`
	VIP                string `json:"vip,omitempty"`
	ZIP                string `json:"zip,omitempty"`
}
