package goserve

import (
	"encoding/json"
)

//Asset is for the Asset table
type Asset struct {
	Status                    string      `json:"__status,omitempty"`
	AquisitionMethod          string      `json:"acquisition_method,omitempty"`
	ActiveTo                  bool        `json:"active_to,omitempty"`
	AssetTag                  string      `json:"asset_tag,omitempty"`
	Assigned                  string      `json:"assigned,omitempty"`
	AssignedTo                string      `json:"assigned_to,omitempty"`
	Beneficiary               string      `json:"beneficiary,omitempty"`
	CheckedIn                 string      `json:"checked_in,omitempty"`
	CheckedOut                string      `json:"checked_out,omitempty"`
	CI                        string      `json:"ci,omitempty"`
	Comments                  string      `json:"comments,omitempty"`
	Company                   string      `json:"company,omitempty"`
	Cost                      float64     `json:"cost,omitempty"`
	CostCenter                string      `json:"cost_center,omitempty"`
	DeliveryDate              string      `json:"delivery_date,omitempty"`
	Department                string      `json:"department,omitempty"`
	DepreciatedAmount         float64     `json:"depreciated_amount,omitempty"`
	Depreciation              string      `json:"depreciation,omitempty"`
	DepreciationDate          string      `json:"depreciation_date,omitempty"`
	DisplayName               string      `json:"display_name,omitempty"`
	DisposalReason            string      `json:"disposal_reason,omitempty"`
	Due                       string      `json:"due,omitempty"`
	DueIn                     string      `json:"due_in,omitempty"`
	ExpenditureType           string      `json:"expenditure_type,omitempty"`
	GlAccount                 string      `json:"gl_account,omitempty"`
	InstallDate               string      `json:"install_date,omitempty"`
	InstallStatus             json.Number `json:"install_status,omitempty"`
	InvoiceNumber             string      `json:"invoice_number,omitempty"`
	Justification             string      `json:"justification,omitempty"`
	LeaseID                   string      `json:"lease_id,omitempty"`
	Location                  string      `json:"location,omitempty"`
	ManagedBy                 string      `json:"managed_by,omitempty"`
	Model                     string      `json:"model,omitempty"`
	ModelCategory             string      `json:"model_category,omitempty"`
	OldStatus                 string      `json:"old_status,omitempty"`
	OldSubstatus              string      `json:"old_substatus,omitempty"`
	OrderDate                 string      `json:"order_date,omitempty"`
	OwnedBy                   string      `json:"owned_by,omitempty"`
	Parent                    string      `json:"parent,omitempty"`
	PONumber                  string      `json:"po_number,omitempty"`
	PreAllocated              bool        `json:"pre_allocated,omitempty"`
	PurchaseDate              string      `json:"purchase_date,omitempty"`
	PurchaseLine              string      `json:"purchase_line,omitempty"`
	Quantity                  json.Number `json:"quantity,omitempty"`
	ReceivingLine             string      `json:"receiving_line,omitempty"`
	RequestLine               string      `json:"request_line,omitempty"`
	ResalePrice               string      `json:"resale_price,omitempty"`
	ReservedFor               string      `json:"reserved_for,omitempty"`
	Residual                  string      `json:"residual,omitempty"`
	ResidualDate              string      `json:"residual_date,omitempty"`
	Retired                   string      `json:"retired,omitempty"`
	RetirementDate            string      `json:"retirement_date,omitempty"`
	SalvageVal                string      `json:"salvage_value,omitempty"`
	SerialNumber              string      `json:"serial_number,omitempty"`
	SkipSync                  bool        `json:"skip_sync,omitempty"`
	Stockroom                 string      `json:"stockroom,omitempty"`
	Substatus                 string      `json:"substatus,omitempty"`
	SupportGroup              string      `json:"support_group,omitempty"`
	SupportedBy               string      `json:"supported_by,omitempty"`
	SysClassName              string      `json:"sys_class_name,omitempty"`
	SysCreatedBy              string      `json:"sys_created_by,omitempty"`
	SysCreatedOn              string      `json:"sys_created_on,omitempty"`
	SysDomain                 string      `json:"sys_domain,omitempty"`
	SysID                     string      `json:"sys_id,omitempty"`
	SysModeCount              json.Number `json:"sys_mod_count,omitempty"`
	SysTags                   string      `json:"sys_tags,omitempty"`
	SysUpdatedBy              string      `json:"sys_updated_by,omitempty"`
	SysUpdatedOn              string      `json:"sys_updated_on,omitempty"`
	ActiveDirectoryOu         string      `json:"u_active_directory_ou,omitempty"`
	AppleModelID              string      `json:"u_apple_model_id,omitempty"`
	AuditedBy                 string      `json:"u_audited_by,omitempty"`
	AvEquipmentType           string      `json:"u_av_equipment_type,omitempty"`
	Bin                       string      `json:"u_bin,omitempty"`
	BudgetIndexCode           string      `json:"u_budget__index_code_,omitempty"`
	CalculatedUser            string      `json:"u_calculated_user,omitempty"`
	Computer                  string      `json:"u_computer,omitempty"`
	ComputerLastLoggedIn      string      `json:"u_computer_last_logged_in,omitempty"`
	ComputerName              string      `json:"u_computer_name,omitempty"`
	CurrentLumenBrightness    int         `json:"u_current_lumen_brightness,omitempty"`
	DeviceAdMembership        string      `json:"u_device_ad_membership,omitempty"`
	DeviceID                  string      `json:"u_device_id,omitempty"`
	DiscountAmount            json.Number `json:"u_discount_amt,omitempty"`
	Donated                   string      `json:"u_donated,omitempty"`
	DonatedTo                 string      `json:"u_donated_to,omitempty"`
	FinalPrice                json.Number `json:"u_final_price,omitempty"`
	Frequency                 string      `json:"u_frequency,omitempty"`
	IndividualDiscount        string      `json:"u_indiv_discount,omitempty"`
	IPAddress                 string      `json:"u_ip_address,omitempty"`
	LampLife                  string      `json:"u_lamp_life,omitempty"`
	LampLifeChecked           string      `json:"u_lamp_life_checked,omitempty"`
	LaptopAssignmentNumber    string      `json:"u_laptop_assignment_number,omitempty"`
	LastLoggedInUser          string      `json:"u_last_logged_in_user,omitempty"`
	LastPhysicalInventoryDate string      `json:"u_last_physical_inventory_date,omitempty"`
	LastRoomPlacement         string      `json:"u_last_room_placement,omitempty"`
	LastService               string      `json:"u_last_service,omitempty"`
	LcmDueDate                string      `json:"u_lcm_due_date,omitempty"`
	LCMReplacementDate        string      `json:"u_lcm_replacement_date,omitempty"`
	LCMReplacementEqmt        bool        `json:"u_lcm_replacement_equipment,omitempty"`
	LcmRitm                   string      `json:"u_lcm_ritm,omitempty"`
	LibertyniversitySurplusS  string      `json:"u_liberty_university_surplus_s,omitempty"`
	LifeSpanYears             int         `json:"u_life_span_years,omitempty"`
	LumenBrightnessAtInstall  string      `json:"u_lumen_brightness_at_install,omitempty"`
	LumenBrightnessChecked    string      `json:"u_lumen_brightness_checked,omitempty"`
	MostRecentDiscov          string      `json:"u_most_recent_discovery,omitempty"`
	OldCostCenter             string      `json:"u_old_cost_center,omitempty"`
	OperatingSystem           string      `json:"u_operating_system,omitempty"`
	OrderedBy                 string      `json:"u_ordered_by,omitempty"`
	PartNumber                string      `json:"u_part_number,omitempty"`
	PharosStationID           string      `json:"u_pharos_station_id,omitempty"`
	PrevAssignedTo            string      `json:"u_previous_assigned_to,omitempty"`
	PrintSalesReceipt         string      `json:"u_print_sales_receipt,omitempty"`
	ProfitCenterName          string      `json:"u_profit_center_name,omitempty"`
	PurchasedBy               string      `json:"u_purchased_by,omitempty"`
	ReadyForSale              string      `json:"u_ready_for_sale,omitempty"`
	ScheduleID                string      `json:"u_schedule_id,omitempty"`
	ServiceContract           string      `json:"u_service_contract,omitempty"`
	ServiceInterval           string      `json:"u_service_interval,omitempty"`
	ServiceLevelIncrement     string      `json:"u_service_level_increment,omitempty"`
	Sold                      string      `json:"u_sold,omitempty"`
	Standard                  string      `json:"u_standard,omitempty"`
	TimeToReady               string      `json:"u_time_to_ready,omitempty"`
	Type                      string      `json:"u_type,omitempty"`
	UpgradeEligibility        bool        `json:"u_upgrade_eligibility,omitempty"`
	UpgradedSpecs             string      `json:"u_upgraded_specs,omitempty"`
	VendorOrderNumber         string      `json:"u_vendor_order_number,omitempty"`
	WarrantyType              string      `json:"u_warranty_type,omitempty"`
	WindowsKey                bool        `json:"u_windows_key,omitempty"`
	WiredMacAddress           string      `json:"u_wired_mac_address,omitempty"`
	WirelessMacAddress        string      `json:"u_wireless_mac_address,omitempty"`
	Variables                 []string    `json:"variables,omitempty"`
	Vendor                    string      `json:"vendor,omitempty"`
	WarrantyExpiration        string      `json:"warranty_expiration,omitempty"`
	WorkNotes                 string      `json:"work_notes,omitempty"`
}

//AssetUpdate is deprecated, only for legacy supported programs
type AssetUpdate struct {
	AssignedTo      string      `json:"assigned_to,omitempty"`
	Comments        string      `json:"comments,omitempty"`
	Location        string      `json:"location,omitempty"`
	ReservedFor     string      `json:"reserved_for,omitempty"`
	InstallStatus   json.Number `json:"install_status,omitempty"`
	Stockroom       string      `json:"stockroom,omitempty"`
	Substatus       string      `json:"substatus,omitempty"`
	WorkNotes       string      `json:"work_notes,omitempty"`
	BudgetIndexCode string      `json:"u_budget__index_code_,omitempty"`
}
