package goserve

//Request is for the Request table
type Request struct {
	Status                    string `json:"__status,omitempty"`
	Active                    string `json:"active,omitempty"`
	ActivityDue               string `json:"activity_due,omitempty"`
	AdditionalAssigneeList    string `json:"additional_assignee_list,omitempty"`
	Approval                  string `json:"approval,omitempty"`
	ApprovalHistory           string `json:"approval_history,omitempty"`
	ApprovalSet               string `json:"approval_set,omitempty"`
	AssignedTo                string `json:"assigned_to,omitempty"`
	AssignmentGroup           string `json:"assignment_group,omitempty"`
	Backordered               string `json:"backordered,omitempty"`
	Billable                  string `json:"billable,omitempty"`
	BusinessDuration          string `json:"business_duration,omitempty"`
	BusinessService           string `json:"business_service,omitempty"`
	CalendarDuration          string `json:"calendar_duration,omitempty"`
	CatItem                   string `json:"cat_item,omitempty"`
	CausedBy                  string `json:"caused_by,omitempty"`
	CloseNotes                string `json:"close_notes,omitempty"`
	ClosedAt                  string `json:"closed_at,omitempty"`
	ClosedBy                  string `json:"closed_by,omitempty"`
	CmdbCi                    string `json:"cmdb_ci,omitempty"`
	Comments                  string `json:"comments,omitempty"`
	Company                   string `json:"company,omitempty"`
	ConfigurationItem         string `json:"configuration_item,omitempty"`
	ContactType               string `json:"contact_type,omitempty"`
	Context                   string `json:"context,omitempty"`
	Contract                  string `json:"contract,omitempty"`
	CorrelationDisplay        string `json:"correlation_display,omitempty"`
	CorrelationID             string `json:"correlation_id,omitempty"`
	DeliveryPlan              string `json:"delivery_plan,omitempty"`
	DeliveryTask              string `json:"delivery_task,omitempty"`
	Description               string `json:"description,omitempty"`
	DueDate                   string `json:"due_date,omitempty"`
	Effort                    string `json:"effort,omitempty"`
	EndDate                   string `json:"end_date,omitempty"`
	Escalation                string `json:"escalation,omitempty"`
	EstimatedDelivery         string `json:"estimated_delivery,omitempty"`
	ExpectedStart             string `json:"expected_start,omitempty"`
	FollowUp                  string `json:"follow_up,omitempty"`
	GroupList                 string `json:"group_list,omitempty"`
	Impact                    string `json:"impact,omitempty"`
	Knowledge                 string `json:"knowledge,omitempty"`
	Location                  string `json:"location,omitempty"`
	MadeSLA                   string `json:"made_sla,omitempty"`
	Number                    string `json:"number,omitempty"`
	OpenedAt                  string `json:"opened_at,omitempty"`
	OpenedBy                  string `json:"opened_by,omitempty"`
	Order                     string `json:"order,omitempty"`
	OrderGuide                string `json:"order_guide,omitempty"`
	Parent                    string `json:"parent,omitempty"`
	Price                     string `json:"price,omitempty"`
	Priority                  string `json:"priority,omitempty"`
	Quantity                  string `json:"quantity,omitempty"`
	QuantitySourced           string `json:"quantity_sourced,omitempty"`
	ReassignmentCount         string `json:"reassignment_count,omitempty"`
	Received                  string `json:"received,omitempty"`
	RecurringFrequency        string `json:"recurring_frequency,omitempty"`
	RecurringPrice            string `json:"recurring_price,omitempty"`
	RemainingEffort           string `json:"remaining_effort,omitempty"`
	Request                   string `json:"request,omitempty"`
	RequestedFor              string `json:"requested_for,omitempty"`
	ScCatalog                 string `json:"sc_catalog,omitempty"`
	ShortDescription          string `json:"short_description,omitempty"`
	Skills                    string `json:"skills,omitempty"`
	SLADue                    string `json:"sla_due,omitempty"`
	Sourced                   string `json:"sourced,omitempty"`
	Stage                     string `json:"stage,omitempty"`
	StartDate                 string `json:"start_date,omitempty"`
	State                     string `json:"state,omitempty"`
	SysClassName              string `json:"sys_class_name,omitempty"`
	SysCreatedBy              string `json:"sys_created_by,omitempty"`
	SysCreatedOn              string `json:"sys_created_on,omitempty"`
	SysDomain                 string `json:"sys_domain,omitempty"`
	SysID                     string `json:"sys_id,omitempty"`
	SysModCount               string `json:"sys_mod_count,omitempty"`
	SysTags                   string `json:"sys_tags,omitempty"`
	SysUpdatedBy              string `json:"sys_updated_by,omitempty"`
	SysUpdatedOn              string `json:"sys_updated_on,omitempty"`
	TimeWorked                string `json:"time_worked,omitempty"`
	Type                      string `json:"type,omitempty"`
	UAccessories              string `json:"u_accessories,omitempty"`
	UAccountable              string `json:"u_accountable,omitempty"`
	UAsset                    string `json:"u_asset,omitempty"`
	UAssetReturned            string `json:"u_asset_returned,omitempty"`
	UAssignedUser             string `json:"u_assigned_user,omitempty"`
	UAssignmentDepartment     string `json:"u_assignment_department,omitempty"`
	UAssignmentDivision       string `json:"u_assignment_division,omitempty"`
	UAssignmentOrganization   string `json:"u_assignment_organization,omitempty"`
	UAssignmentTeam           string `json:"u_assignment_team,omitempty"`
	UAuthorizedPerson         string `json:"u_authorized_person,omitempty"`
	UBaselineDueDate          string `json:"u_baseline_due_date,omitempty"`
	UBenefitingCostCenter     string `json:"u_benefiting_cost_center,omitempty"`
	UBenefitingDepartment     string `json:"u_benefiting_department,omitempty"`
	UBoolean1                 string `json:"u_boolean_1,omitempty"`
	UBoolean2                 string `json:"u_boolean_2,omitempty"`
	UBoolean3                 string `json:"u_boolean_3,omitempty"`
	UBoolean4                 string `json:"u_boolean_4,omitempty"`
	UBudgetYear               string `json:"u_budget_year,omitempty"`
	UCausedByTask             string `json:"u_caused_by_task,omitempty"`
	UContactNumber            string `json:"u_contact_number,omitempty"`
	UDemandRequest            string `json:"u_demand_request,omitempty"`
	UDepartment               string `json:"u_department,omitempty"`
	UDepotLocation            string `json:"u_depot_location,omitempty"`
	UDeviceProblem            string `json:"u_device_problem,omitempty"`
	UDeviceType               string `json:"u_device_type,omitempty"`
	UDisposition              string `json:"u_disposition,omitempty"`
	UDivision                 string `json:"u_division,omitempty"`
	UDueDateChangeCount       string `json:"u_due_date_change_count,omitempty"`
	UEmailCreation            string `json:"u_email_creation,omitempty"`
	UEscalatedAt              string `json:"u_escalated_at,omitempty"`
	UEscalatedBy              string `json:"u_escalated_by,omitempty"`
	UExternalSysID            string `json:"u_external_sys_id,omitempty"`
	UFiberDocumentationChange string `json:"u_fiber_documentation_change,omitempty"`
	UFinalMetric              string `json:"u_final_metric,omitempty"`
	UFinalMetricCode          string `json:"u_final_metric_code,omitempty"`
	UFinalPerformance         string `json:"u_final_performance,omitempty"`
	UFundingDepartment        string `json:"u_funding_department,omitempty"`
	UHardwareQuote            string `json:"u_hardware_quote,omitempty"`
	UInstructions             string `json:"u_instructions,omitempty"`
	UInventoryOrderTracking   string `json:"u_inventory_order_tracking,omitempty"`
	UJiraID                   string `json:"u_jira_id,omitempty"`
	UManufacturer             string `json:"u_manufacturer,omitempty"`
	UNewDesktop               string `json:"u_new_desktop,omitempty"`
	UOnHoldReason             string `json:"u_on_hold_reason,omitempty"`
	UOnsiteStatus             string `json:"u_onsite_status,omitempty"`
	UOrganization             string `json:"u_organization,omitempty"`
	UOwner                    string `json:"u_owner,omitempty"`
	UPassword                 string `json:"u_password,omitempty"`
	UPoNumber                 string `json:"u_po_number,omitempty"`
	UProduct                  string `json:"u_product,omitempty"`
	UPurchaseOrderNumber      string `json:"u_purchase_order_number,omitempty"`
	URank                     string `json:"u_rank,omitempty"`
	UReformat                 string `json:"u_reformat,omitempty"`
	UReleasePackage           string `json:"u_release_package,omitempty"`
	UReplaced                 string `json:"u_replaced,omitempty"`
	URequestedFor             string `json:"u_requested_for,omitempty"`
	URequestedForOrganization string `json:"u_requested_for_organization,omitempty"`
	UResolvedAt               string `json:"u_resolved_at,omitempty"`
	UResolvedBy               string `json:"u_resolved_by,omitempty"`
	UResolvedDuration         string `json:"u_resolved_duration,omitempty"`
	UScheduleID               string `json:"u_schedule_id,omitempty"`
	USerialNumber             string `json:"u_serial_number,omitempty"`
	USlaType                  string `json:"u_sla_type,omitempty"`
	USoftware                 string `json:"u_software,omitempty"`
	Substate                  string `json:"u_substate,omitempty"`
	UTaskScheduler            string `json:"u_task_scheduler,omitempty"`
	UTemplate                 string `json:"u_template,omitempty"`
	UUrl                      string `json:"u_url,omitempty"`
	UValidated                string `json:"u_validated,omitempty"`
	UVendor                   string `json:"u_vendor,omitempty"`
	UWalkinStatus             string `json:"u_walkin_status,omitempty"`
	UWiCustDisplay            string `json:"u_wi_cust_display,omitempty"`
	UWiPrimaryTech            string `json:"u_wi_primary_tech,omitempty"`
	UponApproval              string `json:"upon_approval,omitempty"`
	UponReject                string `json:"upon_reject,omitempty"`
	Urgency                   string `json:"urgency,omitempty"`
	UserInput                 string `json:"user_input,omitempty"`
	Variables                 string `json:"variables,omitempty"`
	WorkEffort                string `json:"work_effort,omitempty"`
	WorkEnd                   string `json:"work_end,omitempty"`
	WorkNotes                 string `json:"work_notes,omitempty"`
	WorkStart                 string `json:"work_start,omitempty"`
}
